"""
Disclaimer/Terms Screen for AI Sprite Creator.

Shows a first-run disclaimer requiring user acknowledgment that they
accept responsibility for AI-generated content.
"""

import json
import tkinter as tk
from tkinter import ttk
from datetime import datetime
from pathlib import Path
from typing import Optional

from ..config import (
    CONFIG_PATH,
    BG_COLOR,
    TEXT_COLOR,
    TEXT_SECONDARY,
    ACCENT_COLOR,
    TITLE_FONT,
    SECTION_FONT,
    BODY_FONT,
    SMALL_FONT,
)
from .tk_common import (
    apply_dark_theme,
    apply_window_size,
    create_primary_button,
    create_secondary_button,
    create_help_button,
)


DISCLAIMER_TITLE = "Terms of Use & Age Verification"

DISCLAIMER_TEXT = """Welcome to AI Sprite Creator

This tool uses Google's Gemini AI to generate character sprites for visual novels and games.

IMPORTANT: AGE REQUIREMENT
By using this software, you confirm that you are at least 18 years of age. All characters generated by this tool are intended to represent adults (18 years or older). You agree NOT to use this tool to create, request, or generate any content depicting minors in any context.

By using this software, you acknowledge and agree that:

1. Adult Users Only
   You confirm that you are at least 18 years old. This tool is not intended for use by minors.

2. Adult Characters Only
   All character sprites generated by this tool are intended to represent characters who are 18 years of age or older. You agree not to use this tool to create content depicting minors.

3. AI-Generated Content
   You are solely responsible for reviewing, moderating, and using any content generated by this tool. AI systems can produce unexpected or inappropriate results.

4. Appropriate Use
   This tool is designed for creating character archetypes suitable for visual novels and games. You agree to use it responsibly and in compliance with all applicable laws.

5. No Warranty & Limitation of Liability
   This software is provided "AS-IS" without warranty of any kind. THE DEVELOPER(S) SHALL NOT BE HELD LIABLE for any damages, claims, or consequences arising from the use of this software or any content generated by it. You assume all responsibility for your use of this tool and any content you create with it.

6. API Usage
   You will use your own Gemini API key and are responsible for complying with Google's terms of service and usage policies.

7. Content Review
   You agree to review all generated content before using it in your projects and ensure it complies with applicable laws and platform policies."""


DISCLAIMER_HELP_TEXT = """Why This Disclaimer?

This tool generates AI character images, which requires clear terms of use.

Age Verification (18+):
- You must be 18 or older to use this tool
- All generated characters are intended to be adults
- Creating content depicting minors is strictly prohibited

Your Responsibilities:
- You control what prompts are used
- You review all generated content
- You decide what to keep or discard
- You're responsible for how content is used

Liability:
- The developer is not responsible for content you create
- You assume all legal responsibility for your use
- AI systems can produce unexpected results

The tool includes safety measures and content filters, but no system is perfect. Always review generated sprites before using them.

Your acceptance is stored locally and you won't see this screen again unless you clear your configuration file (~/.st_gemini_config.json)."""


class DisclaimerWindow:
    """
    First-run disclaimer window requiring user acknowledgment.
    """

    def __init__(self):
        self.root = tk.Tk()
        self.root.title(DISCLAIMER_TITLE)
        self.root.protocol("WM_DELETE_WINDOW", self._on_decline)

        # Apply dark theme and sizing
        apply_dark_theme(self.root)
        apply_window_size(self.root, "compact")

        # Make window slightly taller for all content
        self.root.update_idletasks()
        current_geo = self.root.geometry()
        # Parse and adjust height
        parts = current_geo.split("+")
        size_part = parts[0]
        w, h = size_part.split("x")
        new_h = int(int(h) * 1.15)  # 15% taller
        self.root.geometry(f"{w}x{new_h}+{parts[1]}+{parts[2]}")

        self._accepted = False
        self._checkbox_var = tk.BooleanVar(value=False)

        self._build_ui()

    def _build_ui(self):
        """Build the disclaimer UI."""
        # Main container
        main_frame = tk.Frame(self.root, bg=BG_COLOR, padx=30, pady=24)
        main_frame.pack(fill="both", expand=True)

        # Header with help button
        header_frame = tk.Frame(main_frame, bg=BG_COLOR)
        header_frame.pack(fill="x", pady=(0, 16))

        title_label = tk.Label(
            header_frame,
            text=DISCLAIMER_TITLE,
            bg=BG_COLOR,
            fg=TEXT_COLOR,
            font=TITLE_FONT,
        )
        title_label.pack(side="left")

        help_btn = create_help_button(header_frame, "About This Disclaimer", DISCLAIMER_HELP_TEXT)
        help_btn.pack(side="right")

        # Scrollable text area
        text_frame = tk.Frame(main_frame, bg=BG_COLOR)
        text_frame.pack(fill="both", expand=True, pady=(0, 16))

        # Text widget with scrollbar
        text_widget = tk.Text(
            text_frame,
            wrap="word",
            bg="#1E1E1E",
            fg=TEXT_SECONDARY,
            font=SMALL_FONT,
            relief="flat",
            highlightthickness=1,
            highlightbackground="#444444",
            padx=12,
            pady=12,
        )
        text_widget.insert("1.0", DISCLAIMER_TEXT)
        text_widget.configure(state="disabled")

        scrollbar = ttk.Scrollbar(text_frame, orient="vertical", command=text_widget.yview)
        text_widget.configure(yscrollcommand=scrollbar.set)

        text_widget.pack(side="left", fill="both", expand=True)
        scrollbar.pack(side="right", fill="y")

        # Checkbox
        checkbox_frame = tk.Frame(main_frame, bg=BG_COLOR)
        checkbox_frame.pack(fill="x", pady=(0, 20))

        checkbox = ttk.Checkbutton(
            checkbox_frame,
            text="I am 18+ years old and agree to these terms",
            variable=self._checkbox_var,
            style="Dark.TCheckbutton",
            command=self._on_checkbox_change,
        )
        checkbox.pack(anchor="w")

        # Buttons
        button_frame = tk.Frame(main_frame, bg=BG_COLOR)
        button_frame.pack(fill="x")

        self._accept_btn = create_primary_button(
            button_frame,
            "Accept & Continue",
            self._on_accept,
            width=18,
        )
        self._accept_btn.pack(side="right", padx=(10, 0))
        self._accept_btn.configure(state="disabled")  # Disabled until checkbox checked

        decline_btn = create_secondary_button(
            button_frame,
            "Decline",
            self._on_decline,
            width=12,
        )
        decline_btn.pack(side="right")

    def _on_checkbox_change(self):
        """Handle checkbox state change."""
        if self._checkbox_var.get():
            self._accept_btn.configure(state="normal")
        else:
            self._accept_btn.configure(state="disabled")

    def _on_accept(self):
        """Handle accept button click."""
        if self._checkbox_var.get():
            self._accepted = True
            self.root.quit()

    def _on_decline(self):
        """Handle decline button click or window close."""
        self._accepted = False
        self.root.quit()

    def run(self) -> bool:
        """
        Run the disclaimer window.

        Returns:
            True if user accepted, False if declined
        """
        self.root.mainloop()
        result = self._accepted
        self.root.destroy()
        return result


def load_config() -> dict:
    """Load configuration from the config file."""
    if CONFIG_PATH.exists():
        try:
            with open(CONFIG_PATH, "r", encoding="utf-8") as f:
                return json.load(f)
        except (json.JSONDecodeError, IOError):
            return {}
    return {}


def save_config(config: dict) -> None:
    """Save configuration to the config file."""
    CONFIG_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(CONFIG_PATH, "w", encoding="utf-8") as f:
        json.dump(config, f, indent=2)


def has_accepted_disclaimer() -> bool:
    """
    Check if the user has previously accepted the disclaimer.

    Returns:
        True if accepted, False otherwise
    """
    config = load_config()
    return config.get("disclaimer_accepted", False)


def record_disclaimer_acceptance() -> None:
    """Record that the user has accepted the disclaimer."""
    config = load_config()
    config["disclaimer_accepted"] = True
    config["disclaimer_accepted_at"] = datetime.now().isoformat()
    save_config(config)


def show_disclaimer_if_needed() -> bool:
    """
    Show the disclaimer window if the user hasn't accepted it yet.

    Returns:
        True if user has accepted (either now or previously), False if declined
    """
    if has_accepted_disclaimer():
        return True

    window = DisclaimerWindow()
    accepted = window.run()

    if accepted:
        record_disclaimer_acceptance()
        return True

    return False


# For testing
if __name__ == "__main__":
    result = show_disclaimer_if_needed()
    print(f"Accepted: {result}")
